### ISSUE TITLE
Mention that tidybulk works with tibble/data.frame input as well

### ISSUE THREAD

**Issue by stemangiola** [tidytranscriptomics-workshops/ismb2021_tidytranscriptomics#13]
@mblue9 I was thinking, it would be nice to start to mention for future workshops what is the news about our ecosystem (e.g. tidybulk now work natively with SE of course), but as a reminder 

Mention that tidybulk works with tibble/data.frame input as well, to give the user the freedom, even with non-standard data, that is hardly describable with SE

**Comment by mblue9** [comment]
Sorry missed seeing and mentioning this! We should add that into the next workshop website so it's also in the documentation.
