### ISSUE TITLE
Create Docker

### ISSUE THREAD

**Issue by mblue9** [tidytranscriptomics-workshops/ismb2021_tidytranscriptomics#17]
@stemangiola I'm going to create a Docker for this workshop as probably good to have a preserved version of this workshop, like the others, for our records.

**Comment by stemangiola** [comment]
Sure today I will activate the secrets

**Comment by mblue9** [comment]
Cool after you add can you rerun this action https://github.com/tidytranscriptomics-workshops/ismb2021_tidytranscriptomics/runs/3149768931?check_suite_focus=true

**Comment by mblue9** [comment]
@stemangiola the Docker image was linked to your personal repo instead of tidytranscriptomics-workshops. I've just created a Docker ID for tidytranscriptomics-workshops now. Can you add the Docker Secret to this organization under Settings as I don't have access? see here:  https://docs.github.com/en/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-an-organization
If it can be done at the organization level then we hopefully won't need to set up the Docker secret anymore for every new repo.

**Comment by mblue9** [comment]
Or we could keep using your personal Docker?

**Comment by mblue9** [comment]
I've just fixed the code to point to the image for this workshop that's in your personal Docker. We can just leave it like that and I'll close this unless you want to use an tidy Docker repo.

**Comment by stemangiola** [comment]
> I've just fixed the code to point to the image for this workshop that's in your personal Docker. We can just leave it like that and I'll close this unless you want to use an tidy Docker repo.

Hello Maria,

now the organisation has the secrets to! It would be good if w can use always the same in the future
