### ISSUE TITLE
To Dos

### ISSUE THREAD

**Issue by mblue9** [tidytranscriptomics-workshops/ismb2021_tidytranscriptomics#3]
- [x] Add in tidyseurat content (@stemangiola are we using  just tidyserurat or tidysinglecellexperiment too, [like ABACBS workshop ](https://stemangiola.github.io/ABACBS2020_tidytranscriptomics/articles/tidytranscriptomics.html#part-2-single-cell-rna-seq-1))
- [x] Review all material and exercises
- [x] Deploy servers (3), install packages, material, create user accounts, test
    - [x] rstudio2 ready
    - [x] rstudio3 ready
    - [x] rstudio4 ready
    - [x] **if make any changes to material: for each of the 3 servers need to git pull in admin account and copy to all users.** Try using add-file-accounts.sh to copy folder, else need to put in /etc/skel and recreate accounts
- [x] Create Zenodo DOI

**Comment by mblue9** [comment]
@stemangiola could you make a Zenodo release for the final workshop material please?

**Comment by stemangiola** [comment]
> @stemangiola could you make a Zenodo release for the final workshop material please?

Sure done, updated README
