### ISSUE TITLE
Error: gist API limit

### ISSUE THREAD

**Issue by mblue9** [tidytranscriptomics-workshops/ismb2021_tidytranscriptomics#7]
To note here there's a chance some people at the workshop may experience an error with the pseudobulk part due to use of the gist as got this error below when doing the performance testing. Basically only 60 requests are allowed per hour so if we have >60 participants or some people run the code more than once, people may see this error below.

To fix:
1) set up authentication with the workshop repo for this but don't know how/if that's possible
2) remove the gist and either provide the function in the Rmd or add to tidybulk

```
Error: <github_error in gh_process_response(raw): 
GitHub API error (403): 
Message: API rate limit exceeded for 115.146.84.83. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
Read more at https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting>
$calls
$calls[[1]]
devtools::source_gist("889e4089a0e5ca2649d3c9164e3b542e")
```

**Comment by stemangiola** [comment]
We can bring the function inside.  I can do it tomorrow,  or feel free of
course if you gave the bandwidth.

**Comment by mblue9** [comment]
>We can bring the function inside.  I can do it tomorrow,  or feel free of
course if you gave the bandwidth.

Ok I'll do it today if I get a chance.
