### ISSUE TITLE
Image blured

### ISSUE THREAD

**Issue by stemangiola** [tidytranscriptomics-workshops/ismb2021_tidytranscriptomics#9]
Hello @mblue9, for some reason I see this image out of focus

![image](https://user-images.githubusercontent.com/7232890/126061552-89970341-10c0-46cb-8b7d-cf42520bc0f9.png)

**Comment by mblue9** [comment]
Ah yes, I got it from here https://www.storybench.org/getting-started-with-tidyverse-in-r/
I think I just saved and cropped but I'll see if I can get it less blurry.
Or if you know of another one we could use let me know.

**Comment by mblue9** [comment]
It's less blurry here https://github.com/tidytranscriptomics-workshops/ismb2021_tidytranscriptomics/blob/101cb59f36134e8609aa60dd5ef1b73d199e90a2/inst/vignettes/tidyverse.png
